services:
  # postgres: # Commented out - using remote database
  #   image: postgres:alpine
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql